name: hexlet-ci-app
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 19, 20]
    name: ${{ matrix.node }}  
    steps:
      - uses: actions/checkout@v3
      - name: Setup-node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Setup-project
        run: make setup
      - name: Run test
        run: make test
      - name: Run linter
        run: make lint
  security-check:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects 
